"""Barnard classification system and retention flags."""

# Barnard Medical Subject Heading Classification
BARNARD = {
    "A": "Reference", "AA": "Encyclopedias", "AB": "Scientific and medical dictionaries", "AC": "Directories", "AR": "Education, Teaching",
    "B": "Natural Science", "BA": "Scientific literature", "BB": "Statistics", "BC": "Chemistry", "BCB": "Biochemistry", "BCC": "Clinical chemistry",
    "BD": "Nutrition", "BI": "Microscopy", "BJ": "Biology", "BJC": "Molecular biology", "BJS": "Evolution", "BJT": "Genetics", "BJX": "Ecology",
    "BK": "Botany", "BL": "Zoology", "BM": "Anatomy", "BN": "Histology", "BQ": "Physiology",
    "C": "Internal Medicine", "CBA": "Medical education", "CBE": "Medical ethics", "CBN": "General practice", "CBP": "Group practice", "CBX": "Nursing", "CZ": "Traditional medicine",
    "D": "History of Medicine",
    "E": "Epidemiology", "EA": "Disease ecology", "EB": "Epidemiology", "EC": "Disease surveillance", "EH": "Demography", "EK": "Mortality", "EL": "Mortality", "EP": "Medical geography", "EV": "Human ecology",
    "G": "Toxicology", "GK": "Food poisoning", "GL": "Venomous animals",
    "H": "Immunology, Infectious diseases", "HD": "Immunology", "HG": "Immunodiagnosis", "HI": "Vaccination", "HW": "Infectious diseases",
    "I": "Mycology",
    "J": "Bacteriology", "JC": "Tuberculosis", "JD": "Leprosy", "JI": "Gonorrhea", "JJ": "Bacterial meningitis", "JK": "Cholera", "JM": "Tetanus", "JN": "Plague", "JP": "Brucellosis", "JS": "Salmonelloses", "JX": "Treponematoses", "JYC": "Lyme disease", "JZ": "Leptospiroses",
    "K": "Virology", "KA": "Rickettsioses", "KG": "Chlamydia", "KGJ": "Trachoma", "KI": "Smallpox", "KK": "Rabies", "KP": "Arboviral diseases", "KPA": "Yellow fever", "KPD": "Dengue", "KPH": "Hemorrhagic fever", "KQ": "Encephalitis", "KR": "Retroviruses", "KRC": "HIV, AIDS", "KS": "Hepatitis", "KT": "Poliomyelitis",
    "L": "Parasitology", "LA": "Protozoology", "LC": "Babesiasis", "LD": "Coccidiasis", "LDC": "Cryptosporidiasis", "LDP": "Pneumocystosis", "LE": "Toxoplasmosis", "LF": "Malaria", "LL": "Amebiasis", "LN": "Sleeping sickness", "LNX": "Animal trypanosomiasis", "LP": "Chagas disease", "LQ": "Leishmaniasis", "LV": "Giardiasis",
    "M": "Helminthology", "MH": "Schistosomiasis", "MK": "Echinococcosis", "MQ": "Ascariasis", "MQS": "Strongyloidiasis", "MR": "Ankylostomiasis", "MS": "Filariases", "MU": "Onchocerciasis", "MV": "Trichinelliasis",
    "N": "Entomology", "NB": "Ectoparasites", "NC": "Vector-borne diseases", "ND": "Vector control", "NDI": "Insecticides", "NDY": "Biological control", "NG": "Mites", "NGT": "Ticks", "NK": "Bugs", "NL": "Flies", "NO": "Mosquitoes", "NP": "Simuliidae", "NT": "Tsetse flies",
    "O": "Intermediate Hosts",
    "P": "Pathology", "PM": "Cancer", "PY": "Hematology", "PYB": "Blood groups", "PYE": "Blood transfusion", "PYH": "Anemia", "PYHR": "Hemoglobinopathies", "PYHS": "Sickle cell anemia", "PYK": "Nutritional anemias",
    "Q": "Diagnosis", "QD": "Clinical medicine", "QH": "Laboratory medicine", "QM": "Laboratory medicine", "QR": "Radiology",
    "R": "Pharmacology", "RJ": "Pharmacology", "RN": "Therapeutics", "RNA": "Clinical trials", "RNR": "Drug resistance", "RS": "Drug supply",
    "S": "Public Health", "SA": "Environmental hygiene", "SD": "Water hygiene", "SJA": "Disaster relief", "SO": "Public health", "SOA": "Health organizations", "SOB": "Health information", "SOC": "Health evaluation", "SOCA": "Health research", "SOD": "Health economics", "SOE": "Health financing", "SOF": "Health manpower", "SOG": "Hospitals", "SOH": "Health education", "SON": "Medical sociology", "SOP": "Migrants health", "SP": "Preventive medicine", "SPA": "Disinfection", "SPZ": "Hospital infections", "SS": "Travel health", "ST": "Urban health", "SW": "Naval health",
    "U": "Medical Specialties", "UB": "Tropical medicine", "UBR": "Tropical medicine", "UH": "Cardiology", "UI": "Neurology", "UJ": "Psychiatry", "UK": "Ophthalmology", "UL": "Oto-rhino-laryngology", "UO": "Respiratory diseases", "UP": "Gastroenterology", "UPT": "Enteric infections", "UQ": "Endocrinology", "UR": "Dermatology", "US": "Urology", "UT": "Sexology", "UTH": "Fertility", "UTT": "Family planning", "UTU": "Sexually transmitted diseases", "UV": "Gynecology", "UW": "Obstetrics", "UWB": "Midwives", "UWE": "Mother and child health", "UX": "Pediatrics", "UY": "Geriatrics",
    "V": "Surgery", "VG": "Anesthesia", "W": "Oral Health",
    "X": "Veterinary Sciences", "XC": "Veterinary medicine", "XE": "Epizootiology", "XH": "Immunology", "XHW": "Infectious diseases", "XJ": "Microbiology", "XK": "Virology", "XL": "Parasitology", "XM": "Helminthology", "XN": "Entomology", "XO": "Zoonoses", "XS": "Hygiene", "XW": "Animal husbandry", "XXB": "Cattle", "XXN": "Small ruminants", "XXO": "Pigs", "XXU": "Poultry", "XXZ": "Wild animals", "XZ": "Laboratory animals",
    "Y": "Agriculture", "YA": "Agriculture", "YC": "Field crops", "YH": "Pest control",
    "Z": "Geography, Sociology", "ZB": "Geography", "ZVM": "Development", "ZVO": "Economics", "ZVP": "Political Science", "ZVU": "Management", "ZVY": "Colonial administration", "ZY": "Population issues", "ZYG": "Population movement",
}

# Retention flags based on Barnard classification
RETENTION_FLAGS = {
    "A": "H3", "AA": "H3", "AB": "H3", "AC": "H3", "AR": "H2",
    "BA": "H2", "BB": "H2", "BC": "H3", "BCB": "H3", "BCC": "H3", "BD": "H2", "BE": "H3", "BF": "H3",
    "BJ": "H2", "BJC": "H2", "BJS": "H2", "BJT": "H2", "BJX": "H2", "BK": "H2", "BL": "H2", "BM": "H3", "BN": "H2", "BQ": "H2",
    "C": "H2", "CBA": "H2", "CBE": "H1", "CBN": "H3", "CBP": "H3", "CBX": "H3", "CZ": "H1",
    "D": "H1",
    "EA": "H2", "EB": "H1", "EC": "H2", "EH": "H2", "EK": "H2", "EL": "H2", "EP": "H2", "EQ": "H2", "ES": "H2", "ET": "H2", "EV": "H2",
    "G": "H2", "GK": "H3", "GL": "H2",
    "H": "H2", "HD": "H2", "HG": "H2", "HI": "H2", "HW": "H1",
    "I": "H2",
    "J": "H2", "JC": "H1", "JD": "H2", "JI": "H2", "JJ": "H2", "JK": "H2", "JM": "H2", "JN": "H2", "JP": "H2", "JS": "H2", "JX": "H2", "JYC": "H2", "JZ": "H2",
    "K": "H2", "KA": "H2", "KG": "H2", "KGJ": "H2", "KI": "H2", "KK": "H2", "KP": "H2", "KPA": "H2", "KPD": "H2", "KPH": "H2", "KQ": "H2", "KR": "H2", "KRC": "H2", "KS": "H2", "KT": "H2",
    "L": "H2", "LA": "H2", "LC": "H2", "LD": "H2", "LDC": "H2", "LDP": "H2", "LE": "H2", "LF": "H1", "LL": "H2", "LN": "H2", "LNX": "H2", "LP": "H2", "LQ": "H2", "LV": "H2",
    "M": "H2", "MH": "H2", "MK": "H2", "MQ": "H2", "MQS": "H2", "MR": "H2", "MS": "H2", "MU": "H2", "MV": "H2", "MW": "H2",
    "N": "H2", "NB": "H2", "NC": "H2", "ND": "H2", "NDI": "H3", "NDY": "H2", "NG": "H2", "NGT": "H2", "NK": "H2", "NL": "H2", "NO": "H2", "NP": "H2", "NT": "H2",
    "O": "H2",
    "P": "H2", "PM": "H2", "PY": "H2", "PYB": "H2", "PYE": "H2", "PYH": "H2", "PYHR": "H2", "PYHS": "H2", "PYK": "H2",
    "Q": "H3", "QA": "H3", "QD": "H3", "QH": "H3", "QM": "H3", "QR": "H3",
    "R": "H3", "RJ": "H3", "RN": "H3", "RK": "H3", "RNA": "H2", "RNR": "H3", "RS": "H3",
    "S": "H2", "SA": "H2", "SB": "H2", "SC": "H2", "SD": "H2", "SJA": "H2", "SO": "H2", "SOA": "H2", "SOB": "H2", "SOC": "H2", "SOCA": "H2", "SOD": "H2", "SOE": "H2", "SOF": "H2", "SOG": "H2", "SOH": "H2", "SON": "H2", "SOP": "H2", "SP": "H2", "SPA": "H2", "SPZ": "H2", "SS": "H2", "ST": "H2", "SW": "H2",
    "U": "H2", "UB": "H1", "UBR": "H1", "UH": "H2", "UI": "H2", "UJ": "H2", "UK": "H2", "UL": "H2", "UO": "H2", "UP": "H2", "UPT": "H2", "UQ": "H2", "UR": "H2", "US": "H2", "UT": "H2", "UTH": "H2", "UTT": "H2", "UTU": "H2", "UV": "H2", "UW": "H2", "UWB": "H2", "UWE": "H2", "UX": "H2", "UY": "H2",
    "V": "H3", "VA": "H3", "VB": "H3", "VC": "H3", "VD": "H3", "VE": "H3", "VF": "H3", "VG": "H3", "W": "H3",
    "X": "H2", "XC": "H2", "XE": "H2", "XH": "H2", "XHW": "H2", "XJ": "H2", "XK": "H2", "XL": "H2", "XM": "H2", "XN": "H2", "XO": "H2", "XS": "H2", "XW": "H3", "XXB": "H3", "XXN": "H3", "XXO": "H3", "XXU": "H3", "XXZ": "H2", "XZ": "H2",
    "Y": "H3", "YA": "H3", "YB": "H3", "YC": "H3", "YH": "H3",
    "Z": "H2", "ZB": "H2", "ZI": "H3", "ZR": "H3", "ZV": "H2", "ZVL": "H2", "ZVM": "H2", "ZVN": "H2", "ZVO": "H2", "ZVP": "H2", "ZVU": "H2", "ZVY": "H2", "ZY": "H2", "ZYG": "H2",
}
